const REPLAY_STORAGE_KEY="ksb_replay_history_v1";
const REPLAY_SCHEMA_VERSION=3;
let activeReplay=null,replayIndex=0,replayTimer=null,currentReplay=null,replayPlayInterval=700,replayVisibilityMode="full",replayDelaySeconds=0;
function cloneReplayValue(v){return JSON.parse(JSON.stringify(v));}
function replaySnapshot(){return {roundWind:gameState.roundWind,handNumber:gameState.handNumber,returnEast:!!gameState.returnEast,honba:gameState.honba,deposit:gameState.deposit,dealer:gameState.dealer,currentSeat:gameState.currentSeat,phase:gameState.phase,points:cloneReplayValue(gameState.points),hands:cloneReplayValue(gameState.hands),rivers:cloneReplayValue(gameState.rivers),melds:cloneReplayValue(gameState.melds),flowers:cloneReplayValue(gameState.flowers),riichi:cloneReplayValue(gameState.riichi),doraIndicators:cloneReplayValue(doraIndicators),uraIndicators:cloneReplayValue(uraIndicators||[]),wallRemaining:wall.length,rinshanRemaining:rinshan.length};}
function beginReplayRecording(){if(!currentReplay||currentReplay.endedAt){currentReplay={schemaVersion:REPLAY_SCHEMA_VERSION,source:"local",visibilityMode:"full",spectatorDelaySeconds:0,id:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,startedAt:new Date().toISOString(),endedAt:null,events:[],result:null,bookmarks:[],viewerSeat:PLAYER_SEAT};}recordReplayEvent("round_start",`${roundLabelText()} 開始`);}
function recordReplayEvent(type,label,extra={}){if(!currentReplay||!gameState)return;currentReplay.events.push({seq:currentReplay.events.length,time:Date.now(),type,label,extra:cloneReplayValue(extra),state:replaySnapshot()});}
function normalizeReplay(raw){if(!raw||!Array.isArray(raw.events))return null;const events=raw.events.filter(e=>e&&typeof e==="object"&&e.state).map((e,i)=>({...e,seq:Number.isFinite(Number(e.seq))?Number(e.seq):i,time:Number(e.time)||Date.now()}));if(!events.length)return null;return {schemaVersion:Number(raw.schemaVersion)||1,source:raw.source||"local",visibilityMode:["full","self","hidden"].includes(raw.visibilityMode)?raw.visibilityMode:"full",spectatorDelaySeconds:Math.max(0,Number(raw.spectatorDelaySeconds)||0),viewerSeat:SEATS.includes(raw.viewerSeat)?raw.viewerSeat:PLAYER_SEAT,id:raw.id||`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,startedAt:raw.startedAt||new Date().toISOString(),endedAt:raw.endedAt||null,events,result:raw.result||null,bookmarks:Array.isArray(raw.bookmarks)?raw.bookmarks.filter(i=>Number.isInteger(i)&&i>=0&&i<events.length):[]};}
function loadReplayHistory(){try{return JSON.parse(localStorage.getItem(REPLAY_STORAGE_KEY)||"[]").map(normalizeReplay).filter(Boolean);}catch(e){return [];}}
function persistReplayHistory(history){localStorage.setItem(REPLAY_STORAGE_KEY,JSON.stringify((history||[]).slice(-20)));}
function replayDisplayName(r,index){const dt=new Date(r.startedAt);const when=Number.isNaN(dt.getTime())?`牌譜${index+1}`:dt.toLocaleString();const count=(r.events||[]).length;return `${when} / ${count}イベント${r.result?" / 終局":""}`;}
function refreshReplayHistorySelect(){const sel=document.getElementById("replayHistorySelect");if(!sel)return;const h=loadReplayHistory();sel.innerHTML="";h.slice().reverse().forEach((r,revIndex)=>{const opt=document.createElement("option");opt.value=r.id;opt.textContent=replayDisplayName(r,h.length-1-revIndex);if(activeReplay&&r.id===activeReplay.id)opt.selected=true;sel.appendChild(opt);});if(!h.length){const opt=document.createElement("option");opt.textContent="保存された牌譜はありません";opt.value="";sel.appendChild(opt);}}
function selectReplayFromHistory(id){stopReplayPlay();const r=loadReplayHistory().find(x=>x.id===id);if(!r)return;activeReplay=r;replayIndex=0;replayVisibilityMode=r.visibilityMode||"full";replayDelaySeconds=Math.max(0,Number(r.spectatorDelaySeconds)||0);syncReplayPrivacyControls();renderReplayFrame();}
function exportActiveReplayJson(){if(!activeReplay)return alert("書き出せる牌譜がありません");const blob=new Blob([JSON.stringify(activeReplay,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`ksb-replay-${activeReplay.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function importReplayJson(event){const file=event.target.files&&event.target.files[0];event.target.value="";if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const replay=normalizeReplay(JSON.parse(reader.result));if(!replay)throw new Error("invalid");replay.id=`import-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;replay.source="import";const h=loadReplayHistory();h.push(replay);persistReplayHistory(h);activeReplay=replay;replayIndex=0;refreshReplayHistorySelect();renderReplayFrame();}catch(e){alert("牌譜JSONを読み込めませんでした");}};reader.readAsText(file);}
function deleteActiveReplay(){if(!activeReplay||!confirm("選択中の牌譜を削除しますか？"))return;const h=loadReplayHistory().filter(x=>x.id!==activeReplay.id);persistReplayHistory(h);activeReplay=h.length?h[h.length-1]:null;replayIndex=0;refreshReplayHistorySelect();renderReplayFrame();}
function saveReplayHistory(){if(!currentReplay||!currentReplay.events.length)return;currentReplay.endedAt=new Date().toISOString();currentReplay.result=gameState.matchResult?cloneReplayValue(gameState.matchResult):null;const history=loadReplayHistory();const idx=history.findIndex(x=>x.id===currentReplay.id);if(idx>=0)history[idx]=currentReplay;else history.push(currentReplay);persistReplayHistory(history);}
function latestReplay(){const h=loadReplayHistory();return currentReplay&&currentReplay.events.length?currentReplay:(h.length?h[h.length-1]:null);}
function openReplayViewer(){activeReplay=latestReplay();replayIndex=0;replayVisibilityMode=activeReplay?.visibilityMode||"full";replayDelaySeconds=Math.max(0,Number(activeReplay?.spectatorDelaySeconds)||0);document.getElementById("replayModal").hidden=false;refreshReplayHistorySelect();syncReplayPrivacyControls();renderReplayFrame();}
function closeReplayViewer(){stopReplayPlay();document.getElementById("replayModal").hidden=true;}
function stopReplayPlay(){if(replayTimer){clearInterval(replayTimer);replayTimer=null;}const b=document.getElementById("replayPlayButton");if(b)b.textContent="再生";}
function toggleReplayPlay(){if(!activeReplay||!activeReplay.events.length)return;if(replayTimer){stopReplayPlay();return;}const b=document.getElementById("replayPlayButton");if(b)b.textContent="停止";replayTimer=setInterval(()=>{if(replayIndex>=replayMaxVisibleIndex()){stopReplayPlay();return;}replayIndex++;renderReplayFrame();},replayPlayInterval);}function setReplaySpeed(v){replayPlayInterval=Math.max(100,Number(v)||700);if(replayTimer){stopReplayPlay();toggleReplayPlay();}}function replayFilteredIndexes(){if(!activeReplay)return[];const type=(document.getElementById("replayTypeFilter")||{}).value||"all";const q=((document.getElementById("replaySearchInput")||{}).value||"").trim().toLowerCase();const max=replayMaxVisibleIndex();return activeReplay.events.map((e,i)=>({e,i})).filter(({e,i})=>i<=max&&(type==="all"||e.type===type)&&(!q||`${e.label} ${JSON.stringify(e.extra||{})}`.toLowerCase().includes(q))).map(x=>x.i);}function jumpReplayIndex(i){stopReplayPlay();replayIndex=Math.max(0,Math.min(Number(i)||0,replayMaxVisibleIndex()));renderReplayFrame();}function toggleReplayBookmark(){if(!activeReplay)return;activeReplay.bookmarks=Array.isArray(activeReplay.bookmarks)?activeReplay.bookmarks:[];const pos=activeReplay.bookmarks.indexOf(replayIndex);if(pos>=0)activeReplay.bookmarks.splice(pos,1);else activeReplay.bookmarks.push(replayIndex);activeReplay.bookmarks.sort((a,b)=>a-b);const h=loadReplayHistory(),idx=h.findIndex(x=>x.id===activeReplay.id);if(idx>=0){h[idx]=activeReplay;persistReplayHistory(h);}renderReplayFrame();}function jumpToNextBookmark(){if(!activeReplay||!activeReplay.bookmarks?.length)return;const next=activeReplay.bookmarks.find(i=>i>replayIndex);jumpReplayIndex(next===undefined?activeReplay.bookmarks[0]:next);}
function setReplayVisibility(v){replayVisibilityMode=["full","self","hidden"].includes(v)?v:"full";renderReplayFrame();}
function setReplayDelay(v){replayDelaySeconds=Math.max(0,Number(v)||0);const max=replayMaxVisibleIndex();if(replayIndex>max)replayIndex=max;renderReplayFrame();}
function replayMaxVisibleIndex(){if(!activeReplay||!activeReplay.events.length)return 0;if(!replayDelaySeconds)return activeReplay.events.length-1;const lastTime=Number(activeReplay.events[activeReplay.events.length-1].time)||0;const cutoff=lastTime-replayDelaySeconds*1000;let max=0;activeReplay.events.forEach((e,i)=>{if((Number(e.time)||0)<=cutoff)max=i;});return max;}
function syncReplayPrivacyControls(){const vis=document.getElementById("replayVisibilitySelect"),delay=document.getElementById("replayDelaySelect");if(vis)vis.value=replayVisibilityMode;if(delay)delay.value=String(replayDelaySeconds);}
function replayHandContainer(tiles,seat){const reveal=replayVisibilityMode==="full"||(replayVisibilityMode==="self"&&seat===(activeReplay?.viewerSeat||PLAYER_SEAT));if(reveal)return replayTileContainer(tiles);const box=document.createElement("div");box.className="replay-hidden-hand";for(let i=0;i<(tiles||[]).length;i++){const back=document.createElement("div");back.className="replay-tile-back";back.title="非公開";box.appendChild(back);}return box;}
function replayFirst(){stopReplayPlay();replayIndex=0;renderReplayFrame();}function replayLast(){stopReplayPlay();if(activeReplay)replayIndex=replayMaxVisibleIndex();renderReplayFrame();}function replayPrev(){stopReplayPlay();replayIndex=Math.max(0,replayIndex-1);renderReplayFrame();}function replayNext(){stopReplayPlay();if(activeReplay)replayIndex=Math.min(replayMaxVisibleIndex(),replayIndex+1);renderReplayFrame();}
function replayTileContainer(tiles){const box=document.createElement("div");box.className="replay-tiles";(tiles||[]).forEach(t=>box.appendChild(tileNode(tileValue(t),"tile small locked")));return box;}
function renderReplayFrame(){const meta=document.getElementById("replayMeta"),stage=document.getElementById("replayStage"),list=document.getElementById("replayEventList");if(!activeReplay||!activeReplay.events.length){meta.textContent="保存された牌譜はありません";stage.innerHTML='<div class="replay-empty">対局を進めるとイベント列として保存されます。</div>';list.innerHTML="";return;}const maxVisible=replayMaxVisibleIndex();replayIndex=Math.max(0,Math.min(replayIndex,maxVisible));const e=activeReplay.events[replayIndex],st=e.state;const delayNote=document.getElementById("replayDelayNote");if(delayNote)delayNote.textContent=replayDelaySeconds?`観戦プレビュー：${replayDelaySeconds}秒ディレイ（${maxVisible+1}/${activeReplay.events.length}イベント公開）`:"";meta.textContent=`${replayIndex+1}/${activeReplay.events.length}　${e.label}　[${activeReplay.source||"local"}/${activeReplay.visibilityMode||"full"}]　${st.returnEast?"返り東 ":""}${st.roundWind}${st.handNumber}局 ${st.honba}本場　山${st.wallRemaining}　供託${st.deposit}`;stage.innerHTML="";const grid=document.createElement("div");grid.className="replay-grid";SEATS.forEach(seat=>{const card=document.createElement("div");card.className="replay-seat";const h=document.createElement("h3");h.textContent=`${SEAT_LABELS[seat]} ${formatPoints(st.points[seat])}点${st.riichi[seat]?" / リーチ":""}`;card.appendChild(h);card.appendChild(replayHandContainer(st.hands[seat],seat));const f=document.createElement("div");f.className="note";f.textContent="抜き花";card.appendChild(f);card.appendChild(replayTileContainer(st.flowers[seat]));const m=document.createElement("div");m.className="note";m.textContent="副露";card.appendChild(m);card.appendChild(replayTileContainer((st.melds[seat]||[]).flatMap(x=>x.tiles||[])));const r=document.createElement("div");r.className="note";r.textContent="河";card.appendChild(r);card.appendChild(replayTileContainer(st.rivers[seat]));grid.appendChild(card);});const d=document.createElement("div");d.className="replay-seat";const dh=document.createElement("h3");dh.textContent="ドラ表示";d.appendChild(dh);d.appendChild(replayTileContainer(st.doraIndicators));grid.appendChild(d);stage.appendChild(grid);const filtered=replayFilteredIndexes();list.innerHTML=filtered.map(i=>{const x=activeReplay.events[i],marked=(activeReplay.bookmarks||[]).includes(i);return `<button onclick="jumpReplayIndex(${i})" class="${i===replayIndex?'active':''} ${marked?'replay-bookmark':''}">${marked?'★ ':''}${i+1}. ${x.label}</button>`;}).join("")||'<div class="replay-empty">条件に合うイベントがありません</div>';const active=[...list.querySelectorAll("button")].find(b=>b.classList.contains("active"));if(active)active.scrollIntoView({block:"nearest"});}
